# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('haslo', models.CharField(max_length=100)),
            ],
        ),
    ]
